### ISSUE TITLE
Question: is there any plan to release newer version?

### ISSUE THREAD

**Issue by volkovs** [amaembo/huntbugs#14]
Hi,

We use pom dependencies and need the fix "HuntBugsMojo: art.getType() checked" to be released.

Do you think you could release current version 0.0.10 (before 0.1.0 which might take more time) in observable future? :)

**Comment by amaembo** [comment]
Hello!

Thank you for the interest to HuntBugs. Ok, I will issue 0.0.10 now. I wanted to finish null-analysis core before release, but have not so much free time now. Currently warnings like NullDereferenceGuaranteed, NullDereferencePossible and NullDereferenceExceptional are known to produce unwanted false-positives. Probably will fix this during the next week.
