### ISSUE TITLE
Mojo: type defined in pom.xml dependency (of pom type) is not resolved

### ISSUE THREAD

**Issue by volkovs** [amaembo/huntbugs#17]
If in pom.xml you have dependency of pom type, then those types are not resolved. I.e.
`
TypeDefinition td = typeReference.resolve(); // td = null;
`

(Replacing pom type dependency to regular jar dependency solves the issue)

**Comment by amaembo** [comment]
Interesting, never used pom-type dependencies. Want to submit a pull-request?

**Comment by volkovs** [comment]
OK, will check how to fix.
