### ISSUE TITLE
FP: Useless void method

### ISSUE THREAD

**Issue by ben-manes** [amaembo/huntbugs#28]
```
The method SingleConsumerQueue.LinearizableNode.await() seems to do nothing useful.
Analysis discovers that void method SingleConsumerQueue.LinearizableNode.await() has non-trivial body, yet does nothing useful. Probably there's some mistake.
```

This is a spin loop watching a volatile field. This would be true if the field was non-volatile, as the JVM could optimize it away as dead code. The volatile introduces a load barrier so that the signal is observed.

```java
volatile boolean done;

void await() {
  while (!done) {}
}
```

**Comment by amaembo** [comment]
I can exclude volatile read from operations w/o side-effect, but spin-loop is usually a bad practice. There are better concurrency primitives which will not burn your CPU uselessly...
